services:
  postgres:
    image: postgres:15-alpine
    container_name: foodie-agents-postgres
    environment:
      POSTGRES_DB: foodie_agents
      POSTGRES_USER: foodie_user
      POSTGRES_PASSWORD: foodie_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodie_user -d foodie_agents"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: foodie-agents-network
